version: "3"
services:
  app:
    image: elixir:1.8.1
    container_name: banking_app
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      DATABASE_URL: db
    working_dir: /app
    command: /bin/sh -c "cd /app && mix local.hex --force && mix local.rebar --force && mix deps.get && mix ecto.setup && mix phx.server"
    links:
      - db
    depends_on:
      - db
  db:
    image: "postgres:11"
    container_name: banking_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - .db:/var/lib/postgresql/data